Speakers list page
DeutscheModelUnitedNations/munify pull request #17
Opened 2023-06-13 20:07 UTC by TadeSF

This PR focusses on a new speakers list page, as well as many structural preparations for the upcoming API integration.

It features new strict Types and provides Test Data that simulates incoming API data responses.

2023-06-17 01:10 UTC, m1212e requested changes
Very nice!

2023-06-17 01:10 UTC, m1212e commented on chase/frontend/components/speakers_list/cueue_list.tsx
filename typo

2023-06-17 01:10 UTC, m1212e commented on chase/frontend/components/speakers_list/cueue_list.tsx
> +    wrapperClassNames += " bg-dmunlight";
We might need to check if postcss allows us to do this or rips out the styles it thinks we maybe dont use. Could you please open an issue with this discussion/code snippet as reference so we can check later?

2023-06-17 01:10 UTC, m1212e commented on chase/frontend/components/speakers_list/queue_block.tsx
This is only used for the dashboard, right?

2023-06-17 01:10 UTC, m1212e commented on chase/frontend/components/speakers_list/speaker_block.tsx
> +      const timeInterval = setInterval(() => {
Interval is never cleared

2023-06-17 01:10 UTC, m1212e commented on chase/frontend/components/speakers_list/speaker_block.tsx
> +  const [animationState, setAnimationState] = React.useState<number>(0);
state never read?

2023-06-17 01:10 UTC, m1212e commented on chase/frontend/custom_types.ts
might be nicer to split this into several modules, but its ok for now. Please keep an eye on this, so it doesnt get messy

2023-06-17 01:12 UTC, m1212e commented
Generally, a few extra comments wouldn't hurt, but this can still have some time until the project structure has settled

2023-06-17 07:20 UTC, TadeSF commented on chase/frontend/app/participant/speakers/page.tsx
> +            listTitle="Rednerliste"
Nope, i18n comes in the next PR ;)

2023-06-17 07:22 UTC, TadeSF commented on chase/frontend/app/participant/speakers/page.tsx
> +// TODO Idea: Create a functionality to add as many speakers lists as needed (not only two fixed ones)
Yeah. Thought of it again tbh and it overcomplicates things for our use case pretty much. So I think this should be an Idea at most for the scope we need to roll this out to other MUNs apart from DMUN

2023-06-17 07:25 UTC, TadeSF commented on chase/frontend/components/speakers_list/cueue_list.tsx
addressed in the next PR already, would ceep it for now to prevent merge conflicts

2023-06-17 07:28 UTC, TadeSF commented on chase/frontend/components/speakers_list/queue_block.tsx
Yes. I wasn't sure where to put it that would make sense. My file structure as I am trying to adapt to now is based on the rule: If a component is used on the dashboard but belongs content wise to a section (like the queue-block – the equivalent to the queue_list for the actual speakers list page), I put it in the speakers list component directory. This way everything related stays together. But I have not implemented that philosophy everywhere yet.

2023-06-18 18:44 UTC, m1212e requested changes

2023-06-18 18:44 UTC, m1212e commented on chase/frontend/components/header_template.tsx
>  export default function HeaderTemplate({
Please use js doc notation to make it appear in parsed content, e.g. intellisense:
```suggestion
/**
    This is a style component. It is used to create a header div for pages Like the dashboard
*/
export default function HeaderTemplate({
```

2023-06-18 21:46 UTC, m1212e approved these changes

2023-06-18 21:46 UTC, merged