Finally bring bun & elysia into the main
DeutscheModelUnitedNations/munify pull request #69
Opened 2023-09-20 13:20 UTC by m1212e

This merges the bun setup & elysia into the main. Sorry for the delay, I hope this makes things easier to work with!

2023-09-20 21:36 UTC, TadeSF commented
Unfortunatly no. I am seeing it for the first time. I'll look into it

2023-10-02 22:53 UTC, m1212e commented
I resolved it, it was caused by mismatching versions in the dependencies. Should be good now!

2023-10-12 10:51 UTC, TadeSF commented
Is this PR ready for review? Sorry I lost track :D

2023-10-16 14:38 UTC, m1212e commented
Hi, yes it is 🗡️

2023-10-18 22:05 UTC, TadeSF requested changes
Thanks for the PR. Finally did manage to look over it. I have just one question. In the PR you revert many changes that I made at the change from FA free to pro. Was that intended or by mistake somehow in the merge process?

2023-10-18 22:05 UTC, TadeSF commented on chase/frontend/components/speakers_list/add_speaker.tsx
Why remove the FA Pro Icons?

2023-10-18 22:05 UTC, TadeSF commented on chase/frontend/components/speakers_list/change_speech_time.tsx
Why remove the FA Pro Icons?

2023-10-18 22:05 UTC, TadeSF commented on chase/frontend/components/speakers_list/queue_list.tsx
Why remove the FA Pro Icons?

2023-10-18 22:05 UTC, TadeSF commented on chase/frontend/components/speakers_list/speaker_block.tsx
Why remove the FA Pro Icons?

2023-10-18 22:05 UTC, TadeSF commented on chase/frontend/components/speakers_list/speech_buttons.tsx
Why remove the FA Pro Icons?

2023-10-18 22:05 UTC, TadeSF commented on chase/frontend/components/voting/cast_vote.tsx
Why remove the FA Pro Icons?

2023-10-18 22:05 UTC, TadeSF commented on chase/frontend/package.json
Why remove the FA Pro Icons? Merge Mistake?

2023-10-18 22:05 UTC, TadeSF commented on chase/frontend/components/voting/waiting_for_results.tsx
Why remove the FA Pro Icons?

2023-10-18 22:05 UTC, TadeSF commented on chase/frontend/components/voting/voting.tsx
Why remove the FA Pro Icons?

2023-10-18 22:05 UTC, TadeSF commented on chase/frontend/components/voting/motions.tsx
Why remove the FA Pro Icons?

2023-10-18 22:05 UTC, TadeSF commented on chase/frontend/components/voting/information_section.tsx
Why remove the FA Pro Icons?

2023-10-18 22:05 UTC, TadeSF commented on chase/frontend/components/voting/country_grid.tsx
Why remove the FA Pro Icons?

2023-10-19 07:26 UTC, m1212e commented on chase/backend/prisma/schema.prisma
This is a cumbersome aspect of relational databases and commonly compensated by creating a so called "seed script" which can be used to populate the database with dummy data. Prisma has some resources on this https://www.prisma.io/docs/guides/migrate/seed-database and we probably should use something like this since it will be necessary to kill the database quite frequently when switching between branches.

2023-10-19 15:57 UTC, TadeSF commented on chase/backend/prisma/schema.prisma
Okay! Then I will try to implement it with the next admin-hub PR and with Data that makes sense in that context. Or do you have other plans?

2023-10-22 22:22 UTC, m1212e commented on chase/backend/prisma/schema.prisma
That sounds great, thanks!

2023-10-24 14:20 UTC, TadeSF approved these changes
Looks good, thank you!

2023-11-28 17:48 UTC, merged

2023-11-28 17:50 UTC, m1212e commented
Finally got it 🎉